Feature/button in header when scrolled
helsingborg-stad/aterbruket-webapp pull request #115
Opened 2021-04-19 14:49 UTC by annaeklov

**Explain the changes you’ve made**
Made button in header show when big button is scrolled by and disappears.
Made the add available again when clicking the "ta bort reservation" text

**Explain why these changes are made**
user friendly to see a button in header when the big button disappears from the screen. makes is easy to haffa/hämta ut wherever you are on the screen.
Remove reservation: because you should be able to change your made and un-reserv it
 
**Explain your solution**
Use addEventListener and removeEventListener on scroll, put href to the button to make it the element and see its position on the screen, and when that disappears a small btn in the header is showing
 
**How to test the changes?**
To test the button show in header-function:
Go to detail page, scroll up and down to see a button in header show when big button disappears. 
Click "haffa-knapp" and see scroll up and down to see "hämta ut"-knapp in header show when big btn disappears in "reserverad-vy"

To test the remove reservation-function:
Click text "ta bort reservation" and the add will go back to "tillgänglig"

2021-04-20 11:37 UTC, rubikuo commented
Det ser så bra ut! bra jobbat!!!

2021-04-21 08:20 UTC, JohannaENilsson approved these changes
Bra jobbat! :)

2021-04-21 08:38 UTC, jonatanhanson requested changes
Overall it looks good and it works as indented, but there's some improvement that can be made.

1. Theres some lint errors in the file that can be fixed:
![Screenshot 2021-04-21 at 10 22 43](https://user-images.githubusercontent.com/21363149/115522000-fd5fcd00-a28b-11eb-8e89-0bc08a6f0864.png)

2. It's bad practice to define TS types as _any_:
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any

3. The button needs some more padding (and perhaps smaller font-size?) to follow the Figma design:
![Screenshot 2021-04-21 at 10 09 17](https://user-images.githubusercontent.com/21363149/115523051-f1c0d600-a28c-11eb-931c-c73643b68752.png)

2021-04-21 12:16 UTC, JohannaENilsson approved these changes

2021-04-21 13:22 UTC, closed without merging