Feature/separate items haffat
helsingborg-stad/aterbruket-webapp pull request #124
Opened 2021-05-03 13:19 UTC by annaeklov

**Explain the changes you’ve made**
Separated the reserved items and the picked up items
Put a button "hämta ut" on the card to make it more user friendly

**Explain why these changes are made**
So it looks like the design. And easier for the user to hämta without going in to the item detail page

**Explain your solution**
I did the function for updateItem inside the card-component, and then the get function to render out the cards right

**How to test the changes?**
- Haffa something
- Go to haffat-page and see that the items are separated depending on its status
- See the hämta-ut button on the reserved items, click it and hope it works

2021-05-03 14:48 UTC, jonatanhanson requested changes
It looks good and works most of the times. But sometimes nothing happens when I click on the button "Haffa ut!". And when I try to click again the app crashes with this error: 
![Screenshot 2021-05-03 at 16 39 06](https://user-images.githubusercontent.com/21363149/116891174-b0d2a500-ac2e-11eb-9cd3-bbd8f49c13e9.png)

Not sure if this is related but i noticed that in the updateItem function there is updateAdvert request, but there is also a createAdvert request at the bottom. 
Why is that? 
![Screenshot 2021-05-03 at 16 21 06](https://user-images.githubusercontent.com/21363149/116891546-20489480-ac2f-11eb-8d09-6bb91a75969d.png)

2021-05-03 15:31 UTC, rubikuo commented
The UX implement looks really great!! I had the same problem as Jonatan there. Had to click twice and got error message even if I have done amplify pull .
<img width="1122" alt="Screen Shot 2021-05-03 at 5 21 24 PM" src="https://user-images.githubusercontent.com/46818235/116897326-6acd0f80-ac35-11eb-9d53-5e280807679f.png">

2021-05-04 11:16 UTC, JohannaENilsson approved these changes
Bra jobbat 👯

2021-05-04 13:55 UTC, jonatanhanson approved these changes

2021-05-04 14:22 UTC, merged